services:

  postgres_students_db:
    image: postgres
    container_name: postgres_students_db
    restart: always
    ports: 
      - 4420:5432
    env_file:
      - ./back-end/.env
    volumes:
    - students_db:/var/lib/postgresql/data
  
  node_students_app:
    container_name: node_students_app
    build: ./back-end
    image: node_students_app_image
    ports:
      - 5000:5000
    depends_on: 
      - postgres_students_db
    env_file:
      - ./back-end/.env
  
  react_students_app:
    container_name: react_students_app
    build: ./front-end
    image: react_students_app
    volumes:
      - build_react:/var/www/html
  
  nginx_students_app:
    container_name: nginx_students_app
    build: ./nginx
    image: nginx_students_app
    ports:
      - 80:80
    volumes:
    - build_react:/var/www/html
    depends_on: 
      - postgres_students_db
      - node_students_app
      - react_students_app
volumes: 
  students_db:
  build_react: